version: '3.1'
services:
  db:
    container_name: Baza_Danych
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: credit_app
    volumes:
      - type: volume
        source: api-postgres-volume
        target: /var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
  customer:
    container_name: SpringBoot_Customer
    build: ./customer
    ports:
    - 8081:8081
    depends_on:
      - db
  product:
    container_name: SpringBoot_Product
    build: ./product
    ports:
    - 8082:8082
    depends_on:
      - db
  credit:
    container_name: SpringBoot_Credit
    build: ./credit
    ports:
      - 8080:8080
    depends_on:
      - db
      - customer
      - product
volumes:
  api-postgres-volume:
