apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customer
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customer
    spec:
      containers:
        - image: kamilspringjava/customer_app
          name: customer-app
          resources: {}
status: {}
